import { Mission, FeedActivity, Mentor } from "./types";

export const missions: Mission[] = [
  {
    id: "m1",
    title: "Decoration Team — International Culture Night",
    club: "University Student Affairs",
    createdBy: "Office of Student Affairs",
    verified: true,
    reward: 150,
    deposit: 0,
    urgency: "high",
    tags: ["Volunteer", "Event", "Decoration"],
    description: "Help set up the main hall, banners, and country booths the day before the event.",
    status: "open",
    postedAgo: "12m",
    applicants: 7,
    category: "task",
    missionCategory: "university_campaign",
    difficulty: "Medium",
    deadline: "May 12",
    volunteerHours: 4,
    certificateProgress: "Event Ambassador Certificate",
    badge: "Leadership Badge",
    skillsDeveloped: ["Leadership", "Communication", "Marketing"],
  },
  {
    id: "m2",
    title: "Help first-year students choose CS electives",
    club: "Senior — Priya K.",
    createdBy: "Priya K. (Senior)",
    verified: true,
    reward: 120,
    deposit: 0,
    urgency: "medium",
    tags: ["Mentorship", "Academic", "Juniors"],
    description: "1-hour group session walking new CS students through electives, FYP tracks, and internships.",
    status: "open",
    postedAgo: "1h",
    applicants: 3,
    category: "mentorship",
    missionCategory: "junior_support",
    difficulty: "Easy",
    deadline: "May 10",
    certificateProgress: "Peer Mentor Certificate",
    badge: "Junior Mentor Badge",
    skillsDeveloped: ["Communication", "Leadership", "Technical"],
  },
  {
    id: "m3",
    title: "Help with Java debugging — concurrency bug",
    club: "Peer Request — Sam T.",
    createdBy: "Sam T.",
    verified: true,
    reward: 60,
    deposit: 0,
    urgency: "high",
    tags: ["Java", "Debugging", "PeerHelp"],
    description: "Stuck on a thread-safety issue in a class assignment. 30–45 min screen-share.",
    status: "open",
    postedAgo: "30m",
    applicants: 4,
    category: "task",
    missionCategory: "peer_support",
    difficulty: "Medium",
    deadline: "May 4",
    certificateProgress: "Peer Support Certificate",
    badge: "Skill Helper Badge",
    skillsDeveloped: ["Technical", "Communication"],
  },
  {
    id: "m4",
    title: "Design posters for Spring Hackathon 2026",
    club: "ACM Student Chapter",
    createdBy: "ACM Student Chapter",
    verified: true,
    reward: 140,
    deposit: 0,
    urgency: "medium",
    tags: ["GraphicDesign", "Figma", "Club"],
    description: "Need 3 A2 posters following the University Blue & Gold palette. Source files required.",
    status: "open",
    postedAgo: "3h",
    applicants: 6,
    category: "task",
    missionCategory: "club_mission",
    difficulty: "Medium",
    deadline: "May 18",
    certificateProgress: "Club Contributor Certificate",
    badge: "Club Supporter Badge",
    skillsDeveloped: ["Design", "Marketing"],
  },
  {
    id: "m5",
    title: "Registration desk — Open Day 2026",
    club: "University Student Affairs",
    createdBy: "Office of Student Affairs",
    verified: true,
    reward: 220,
    deposit: 0,
    urgency: "high",
    tags: ["Volunteer", "OpenDay", "Registration"],
    description: "Run check-in for prospective students and parents. Two 4-hour shifts.",
    status: "open",
    postedAgo: "2h",
    applicants: 5,
    category: "task",
    missionCategory: "university_campaign",
    difficulty: "Easy",
    deadline: "May 24",
    volunteerHours: 4,
    certificateProgress: "Volunteer Excellence Certificate",
    badge: "Leadership Badge",
    skillsDeveloped: ["Communication", "Leadership"],
  },
];

export const feed: FeedActivity[] = [
  { id: "f1", user: "Aanya R.", avatar: "AR", action: "completed", target: "Photography for Robotics Showcase", amount: 60, timeAgo: "just now", kind: "complete" },
  { id: "f2", user: "Marcus L.", avatar: "ML", action: "posted", target: "Tutor needed: Linear Algebra", timeAgo: "2m", kind: "post" },
  { id: "f3", user: "Priya K.", avatar: "PK", action: "released reward to", target: "Devon S. — $80", amount: 80, timeAgo: "5m", kind: "reward" },
  { id: "f4", user: "Sam T.", avatar: "ST", action: "joined", target: "Spring Hackathon poster", timeAgo: "8m", kind: "join" },
  { id: "f5", user: "Chen W.", avatar: "CW", action: "completed", target: "Translate research abstract", amount: 35, timeAgo: "14m", kind: "complete" },
  { id: "f6", user: "Lila O.", avatar: "LO", action: "posted", target: "Logo refresh for Debate Society", timeAgo: "22m", kind: "post" },
];

export const mentors: Mentor[] = [
  { id: "u1", name: "Priya K.", avatar: "PK", major: "CS · Senior", rating: 4.9, sessions: 42, skills: ["Java", "Spring4", "FinalYearProject"], online: true },
  { id: "u2", name: "Devon S.", avatar: "DS", major: "Design · Junior", rating: 4.8, sessions: 28, skills: ["GraphicDesign", "Figma", "Branding"], online: true },
  { id: "u3", name: "Mei H.", avatar: "MH", major: "Math · PhD", rating: 5.0, sessions: 64, skills: ["LinearAlgebra", "Statistics", "Python"], online: false },
  { id: "u4", name: "Jordan B.", avatar: "JB", major: "EE · Senior", rating: 4.7, sessions: 19, skills: ["Embedded", "C++", "Robotics"], online: true },
];
